---
- name: Install required packages
  apt:
    name:
      - curl
      - ca-certificates
    state: present
    update_cache: yes

- name: Create directory for PostgreSQL GPG keys
  file:
    path: /usr/share/postgresql-common/pgdg
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Download PostgreSQL GPG key
  get_url:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    dest: /usr/share/postgresql-common/pgdg/apt.postgresql.org.asc
    mode: '0644'

- name: Add PostgreSQL APT repository
  apt_repository:
    repo: "deb [signed-by=/usr/share/postgresql-common/pgdg/apt.postgresql.org.asc] https://apt.postgresql.org/pub/repos/apt {{ ansible_lsb.codename }}-pgdg main"
    state: present

- name: Update APT package cache
  apt:
    update_cache: yes

- name: Install PostgreSQL 16
  apt:
    name: "postgresql-16"
    state: present

- name: Check if PostgreSQL 16 is installed
  command: "psql --version"
  register: postgres_version
  changed_when: false

- name: Validate PostgreSQL version
  assert:
    that:
      - "'16' in postgres_version.stdout"
    fail_msg: "PostgreSQL 16 is not installed or the version is incorrect."
    success_msg: "PostgreSQL 16 is installed and verified."
