---
- name: Install Fail2Ban
  ansible.builtin.apt:
    name: fail2ban
    state: present
    update_cache: yes

- name: Copy Fail2Ban configuration file
  ansible.builtin.template:
    src: fail2ban_config.j2 
    dest: /etc/fail2ban/jail.local
    mode: '0644'
    owner: root
    group: root
  notify: Restart Fail2Ban

- name: Ensure Fail2Ban service is enabled and started
  ansible.builtin.systemd:
    name: fail2ban
    state: started
    enabled: yes
